language: node_js
node_js:
  - 11
deploy:
  - provider: npm
    api_token: $NPM_API_KEY
    edge: true # opt in to dpl v2
    email: whenderson.github+npm@gmail.com
    on:
      branch: master
  - provider: pages:git
    token: $GITHUB_TOKEN
    edge: true
    on:
      branch: master



